services:
  app:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 10s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    ports:
      - "8000:8000"